---
title: "Multicollinearity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Longley


```{r cars}
library(datasets)
library(tidyverse)
library(broom)
library(viridis)
library(GGally)
library(car)
library(gridExtra)
library(knitr)
library(corrplot)
```

```{r}
df <- longley
str(df)
```

```{r}
#ggpairs(df)
```



```{r}
#now fitting a linear model
model1 <- lm(Employed ~ GNP + Unemployed + Armed.Forces + Population + Year, data = df)
vif(model1)
```


```{r}
#now fitting a linear model again
model2 <- lm(Employed ~ Unemployed + Armed.Forces +Population + Year, data = df)

vif(model2)
```
```{r}

#now fitting a linear model again
model3 <- lm(Employed ~ Unemployed + Armed.Forces +Population, data = df)

vif(model3)

```



## Blood Pressure

```{r}
bloodpress <- read.table("bloodpress.txt", header=T)
```


```{r}
str(bloodpress)
```

```{r}
cor(bloodpress)
```

```{r}
corrplot(cor(bloodpress), type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r}

model.1 <- lm(BP ~ Age + Weight + BSA + Dur + Pulse + Stress, data = bloodpress)
car::vif(model.1)
```

```{r}


model.2 <- lm(BP ~ Age +  BSA + Dur + Pulse + Stress, data = bloodpress)
car::vif(model.2)

```


```{r}
head(bloodpress)

```

```{r}
#plot(bloodpress[, -1])
corrplot(cor(bloodpress[, -1]), method = "number", type = "upper", diag = FALSE)
```

```{r}
summary(bloodpress.lm <- lm(BP ~ . - Pt, data = bloodpress))

```

```{r}
round(vif(bloodpress.lm),2)
```

```{r}
summary(bloodpress.lm2 <- lm(BP ~ . - Pt - BSA, data = bloodpress))
```

```{r}
round(vif(bloodpress.lm2),2)
```


